### ISSUE TITLE
Installation loop at the end

### ISSUE THREAD

**Issue by JohnBerd** [zubroide/gitpab#78] opened 2021-05-31 14:04 UTC
Hello,

I am trying to give a try to this great tool but I still face some issues installing it, your last commit made me go further to the installation, but I get now this error (installed with the Docker command):

gitpab-php | wait-for-it.sh: waiting 180 seconds for db:5432
gitpab-db | 2021-05-31 13:59:36.742 UTC [48] LOG:  incomplete startup packet
gitpab-php | wait-for-it.sh: db:5432 is available after 0 seconds
gitpab-php | PostgreSQL started
gitpab-php | Init project
gitpab-php | 
gitpab-php | In PackageManifest.php line 120:
gitpab-php |                          
gitpab-php |   Undefined index: name  
gitpab-php |                          
gitpab-php | 
gitpab-php exited with code 1

This message loops indefinitely, any idea? 

Thank you

**Comment by mnvx** [comment] 2021-05-31 14:45
Hi. This fixed in #68. Try to git pull and build containers again.

**Comment by JohnBerd** [comment] 2021-05-31 14:51
Thank you for this fast answer, this issue happened after the commit closing the issue #68.

**Comment by mnvx** [comment] 2021-05-31 15:09
Hm. Cant reproduce this. Are you rebuild containers using `--build` option?

**Comment by JohnBerd** [comment] 2021-05-31 15:28
Yes I do, I've tried on a raspberry pi, same issue as well.

**Comment by jtokic** [comment] 2021-06-08 08:42
Same problem here.
ENV variables for GitLab edited in **docker-compose.yml**

**Operating System:**
Ubuntu 18.04.3 LTS
Kernel: Linux 4.15.0-135-generic
Architecture: x86-64

**Docker version:**
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bc
 Built:             Fri Feb  5 15:56:39 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf
  Built:            Fri Feb  5 15:58:24 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Output:**
>user@host:~/gitpab$ docker-compose up --build
Building php
Step 1/30 : FROM node:8 as builder
 ---> 8eeadf3757f4
Step 2/30 : RUN mkdir /frontend
 ---> Using cache
 ---> b78a0fbea82a
Step 3/30 : WORKDIR /frontend
 ---> Using cache
 ---> 5fbedd6ec083
Step 4/30 : COPY ./package.json .
 ---> Using cache
 ---> 0222447327f8
Step 5/30 : COPY ./package-lock.json .
 ---> Using cache
 ---> 6ea3fc972f9e
Step 6/30 : RUN npm ci
 ---> Using cache
 ---> 993e408445a9
Step 7/30 : COPY ./webpack.mix.js ./webpack.mix.js
 ---> Using cache
 ---> 5b5ceaf15277
Step 8/30 : COPY ./resources/assets ./resources/assets
 ---> Using cache
 ---> dee0c629bb87
Step 9/30 : RUN npm run prod
 ---> Using cache
 ---> 78b68c6bd2e1

>Step 10/30 : FROM php:7.1-fpm
 ---> 404422fc039e
Step 11/30 : WORKDIR /var/www/html
 ---> Using cache
 ---> ade80670c851
Step 12/30 : RUN apt update -y     && apt install -y ssh git zip bzip2 wget libmcrypt-dev cron mc
 ---> Using cache
 ---> 706886e7ee79
Step 13/30 : RUN apt update -y     && apt install -y libpq-dev libpng-dev         libjpeg-dev libjpeg-progs libjpeg62 libfftw3-3 libfftw3-dev libwmf-dev         libx11-dev libxt-dev libxext-dev libxml2-dev libfreetype6-dev libexif-dev         libltdl3-dev graphviz pkg-config libperl-dev perl         libz-dev libbz2-dev libmemcached-dev libtidy-dev zlib1g-dev libicu-dev g++     && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql     && docker-php-ext-configure intl     && docker-php-ext-configure gd         --with-freetype-dir=/usr/lib/         --with-png-dir=/usr/lib/         --with-jpeg-dir=/usr/lib/         --with-gd     && docker-php-ext-install pdo_pgsql zip pcntl gd intl mcrypt     && pecl install -o -f redis     && pecl install -o -f memcached     && rm -rf /tmp/pear     && docker-php-ext-enable redis memcached
 ---> Using cache
 ---> b5f054c1aa24
Step 14/30 : COPY --from=composer /usr/bin/composer /usr/bin/composer
 ---> Using cache
 ---> 60746b85792c
Step 15/30 : ENV COMPOSER_ALLOW_SUPERUSER=1
 ---> Using cache
 ---> 342bd56c8da4
Step 16/30 : RUN touch /var/log/cron.log
 ---> Using cache
 ---> 5039b51260da
Step 17/30 : ADD ./docker/php/entrypoint.sh /root/entrypoint.sh
 ---> Using cache
 ---> 5829bba514ae
Step 18/30 : ADD ./docker/wait-for-it.sh /root/wait-for-it.sh
 ---> Using cache
 ---> 7b2ba9dd13e7
Step 19/30 : RUN chmod 755 /root/entrypoint.sh     && chmod 755 /root/wait-for-it.sh
 ---> Using cache
 ---> 7f5629f28f4d
Step 20/30 : COPY ./docker/cron/crontab /etc/cron.d/app
 ---> Using cache
 ---> 2eca582f0d9b
Step 21/30 : RUN crontab /etc/cron.d/app
 ---> Using cache
 ---> ef5cb2c4b654
Step 22/30 : COPY ./composer.json .
 ---> Using cache
 ---> ecdef070ed8c
Step 23/30 : COPY ./composer.lock .
 ---> Using cache
 ---> 20e279124be3
Step 24/30 : RUN composer install --no-dev --no-autoloader
 ---> Using cache
 ---> cfd8b4ca1c9c
Step 25/30 : COPY --from=builder /frontend/public/css ./public/css
 ---> Using cache
 ---> d71db49e9114
Step 26/30 : COPY --from=builder /frontend/public/js ./public/js
 ---> Using cache
 ---> 031c00c4ac56
Step 27/30 : ADD . .
 ---> Using cache
 ---> 96c2d81dc481
Step 28/30 : COPY ./docker/php/.env.template ./.env
 ---> Using cache
 ---> 240fe7b577e9
Step 29/30 : RUN composer dump-autoload
 ---> Using cache
 ---> c6b41be06595
Step 30/30 : ENTRYPOINT ["/root/entrypoint.sh"]
 ---> Using cache
 ---> bccc1e7de416

>Successfully built bccc1e7de416
Successfully tagged gitpab_php:latest
Starting gitpab-db ... done
Recreating gitpab-php ... done
Recreating gitpab-nginx ... done
Attaching to gitpab-db, gitpab-php, gitpab-nginx
gitpab-nginx | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
gitpab-nginx | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
gitpab-db |
gitpab-db | PostgreSQL Database directory appears to contain a database; Skipping initialization
gitpab-db |
gitpab-nginx | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
gitpab-db | 2021-06-08 08:38:44.969 UTC [1] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
gitpab-nginx | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
gitpab-db | 2021-06-08 08:38:44.971 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
gitpab-db | 2021-06-08 08:38:44.971 UTC [1] LOG:  listening on IPv6 address "::", port 5432
gitpab-nginx | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
gitpab-nginx | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
gitpab-db | 2021-06-08 08:38:44.984 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
gitpab-db | 2021-06-08 08:38:45.096 UTC [25] LOG:  database system was shut down at 2021-06-08 08:02:57 UTC
gitpab-db | 2021-06-08 08:38:45.180 UTC [1] LOG:  database system is ready to accept connections
gitpab-db | 2021-06-08 08:38:49.479 UTC [32] LOG:  incomplete startup packet
gitpab-php | Waiting for Postgres...
gitpab-php | wait-for-it.sh: waiting 180 seconds for db:5432
gitpab-php | wait-for-it.sh: db:5432 is available after 0 seconds
gitpab-php | PostgreSQL started
gitpab-php | Init project
gitpab-php |
gitpab-php | In PackageManifest.php line 120:
gitpab-php |
gitpab-php |   Undefined index: name
gitpab-php |
gitpab-php |
gitpab-nginx | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
gitpab-nginx | /docker-entrypoint.sh: Configuration complete; ready for start up
gitpab-nginx | 2021/06/08 08:38:52 [notice] 1#1: using the "epoll" event method
gitpab-nginx | 2021/06/08 08:38:52 [notice] 1#1: nginx/1.21.0
gitpab-nginx | 2021/06/08 08:38:52 [notice] 1#1: built by gcc 10.2.1 20201203 (Alpine 10.2.1_pre1)
gitpab-nginx | 2021/06/08 08:38:52 [notice] 1#1: OS: Linux 4.15.0-135-generic
gitpab-nginx | 2021/06/08 08:38:52 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:4096
gitpab-nginx | 2021/06/08 08:38:52 [notice] 1#1: start worker processes
gitpab-nginx | 2021/06/08 08:38:52 [notice] 1#1: start worker process 30
gitpab-nginx | 2021/06/08 08:38:52 [notice] 1#1: start worker process 31
gitpab-nginx | 2021/06/08 08:38:52 [notice] 1#1: start worker process 32
gitpab-nginx | 2021/06/08 08:38:52 [notice] 1#1: start worker process 33
gitpab-db | 2021-06-08 08:38:52.582 UTC [33] LOG:  incomplete startup packet
^CGracefully stopping... (press Ctrl+C again to force)
Stopping gitpab-nginx   ... done
Stopping gitpab-php     ... done
Stopping gitpab-db      ... done
user@host:~/gitpab$

**Comment by ProCessor00** [comment] 2021-12-28 14:05
Same issue here, running the docker image; ending in this loop:
```
PostgreSQL started

In PackageManifest.php line 120:

                        
  Undefined index: name 
```

**Comment by lokha** [comment] 2022-01-24 07:01
same thing. testing on the last commit
```
gitpab-php | wait-for-it.sh: timeout occurred after waiting 180 seconds for db:5432
gitpab-php | PostgreSQL started
gitpab-php | Init project
gitpab-php |
gitpab-php | In PackageManifest.php line 120:
gitpab-php |
gitpab-php |   Undefined index: name
gitpab-php |
gitpab-php |
gitpab-php exited with code 1
```

**Comment by mnvx** [comment] 2022-11-15 21:35
Updated deploy scripts

**Closed by mnvx** 2022-11-15 21:35 UTC
